### PR TITLE
CPS module

### PR DESCRIPTION
**Pull request by hayleefay**
The `file_names_for_range` function was first written assuming that the input would be `jan16` rather than `0116`. I am happy to change it, but I wanted to ask first about leaving it this way and demanding that format from the user since this is the format that the file names are in and seems more consistent.

As for style, would you rather I create all supplementary functions within `hrs_by_age.py` or create a separate file for each function (or at least task)?

### CODE REVIEW

**Comment by rickecon** [comment]
@hayleefay. I initially wanted the beginning and ending date inputs as `'0116'`, but then I started thinking it would be easier to just use the `'jan16'` format because that is the format the CPS files are in. I am fine with whichever way you think is most intuitive.

With regard to function nesting, I think the best practice would be to list each function separately within the module `hrs_by_age.py` without nesting functions within functions. In this way, each function in the module is loaded when someone does `import hrs_by_age`.

**Comment by hayleefay** [comment]
@rickecon In the current version, once the zip files are downloaded and unzipped, they are saved into the working directory. Would you rather the files not be saved? I can look into reading them without saving them to the disk, or, possibly the best option, just creating temporary files and then deleting them once the vector has been returned.

**Comment by rickecon** [comment]
@hayleefay If a user chooses the `web` option, I think we will want to treat the files as temporary files so that they are deleted after the function returns its objects.

**Comment by hayleefay** [comment]
@rickecon I think this is pretty close. Feel free to test it. A sample test call is below:
`hrs_by_age('feb16', 'may16', directory='~/Downloads/', web=False, graph=True, age_bins=np.array([15,25,35,45,55,65,75]), l_tilde=40)`

**Comment by hayleefay** [comment]
Matplotlib has been added as an option for plotting. I added a new parameter that can be passed in called `graph_type` that will stipulate which plots to generate. The default is Bokeh but if you set `graph_type = 'plt'` then matplotlib graphs will be generated instead. Open to suggestions for another way to handle this.

**Comment by rickecon** [comment]
@hayleefay . When I import the module and run the following code it takes nearly 10 minutes to finish executing or deliver anything. I ran the following
```python
import hrs_by_age as hba

hba.hrs_by_age('jan15', 'jan17', web=True, graph=True)
```
Is that time normal for a download of 25 files? It did produce a nice Bokeh plot in my browser at the end. But it also threw the following error from my terminal.
```python
0:101: execution error: "file:///Users/rwe/Documents/Economics/Tools/CPS_hrs_age/OUTPUT/images/hrs_by_age.html" doesn’t understand the “open location” message. (-1708)
```
Do you get that? What do you think that is coming from?

**Comment by hayleefay** [comment]
@rickecon Yes, the web download is quite slow, but when I run that command it took 4.5 minutes on my computer. I can look into ways to make it faster and also add a progress bar to the terminal.

I do get that error when it opens the browser -- I read about it yesterday and it appears to be an Apple error from the latest OS release in mid-May. It is apparently fixed in the next release and, in the meantime, all of the patches are at a per user basis (like changing your system's default browser). [You can read about it here.](http://www.andrewjaffe.net/blog/2017/05/python-bug-hunt.html)

**Pull request merged**
